### ISSUE TITLE
Crash during server start

### ISSUE THREAD

**Issue by AlexCreeper25** [LavaPowered/Lava#10]
I get this error when I start the server:

`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/MarkedYAMLException
	at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:106)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:17)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:193)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:639)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.MarkedYAMLException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Caused by: java.lang.NullPointerException
`

If you need any more info tell me

**Comment by GMatrixGames** [comment]
What build are you using?

**Comment by AlexCreeper25** [comment]
I'm using the latest Jenkins 1.12.2 build

**Comment by GMatrixGames** [comment]
We have 2 Jenkins servers, what's the URL? Codemc or OpenProcesses

**Comment by AlexCreeper25** [comment]
CodeMC

**Comment by GMatrixGames** [comment]
Use the build from OpenProcesses

On Sun, Aug 18, 2019, 11:11 AM AlexCreeper25 <notifications@github.com<mailto:notifications@github.com>> wrote:

CodeMC

**Comment by AlexCreeper25** [comment]
Alright Imma try it

**Comment by AlexCreeper25** [comment]
I just tried with the OpenProcesses build and i got the same error

**Comment by GMatrixGames** [comment]
If you join our discord, I can help you a bit better
