### ISSUE TITLE
World Guard v6.2.2 PlayerInteractEvent

### ISSUE THREAD

**Issue by GGothicRide** [LavaPowered/Lava#14]
[22:13:25] [Server thread/ERROR] [Lava]: Could not pass event InventoryMoveItemEvent to WorldGuard v6.2.2-SNAPSHOT;8eeab68
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:64) ~[EventExecutor.class:git-Lava-fda5d89-ALPHA-LTT1]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Lava-fda5d89-ALPHA-LTT1]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:477) [SimplePluginManager.class:git-Lava-fda5d89-ALPHA-LTT1]
at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:165) [VanillaInventoryCodeHooks.class:git-Lava-fda5d89-ALPHA-LTT1]
at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:231) [avw.class:?]
at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:174) [avw.class:?]
at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:156) [avw.class:?]
at net.minecraft.world.World.func_72939_s(World.java:2104) [amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:854) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:465) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at com.sk89q.worldguard.bukkit.listener.debounce.legacy.InventoryMoveItemEventDebounce$BlockMaterialKey.hashCode(InventoryMoveItemEventDebounce.java:118) ~[?:?]

**Comment by GMatrixGames** [comment]
This issue is unable to be fixed on our end, WG and WE needs to add support for extra items and blocks other than vanilla.
